Repository abahachuk/ptushki-backend, pull requests merged in 2019-05, with the labels that each got.

#25 EPMCUXDA-6483 add fixturesmeter
  src/db/run-fixtures.ts
  src/utils/clean-write-line.ts
Labels: enhancement

#29 Epmcuxda 6640. Observation List POC
  config/default.ts
  src/controllers/observation-controller.ts
  src/entities/observation-entity.ts
  src/routes.ts
  src/services/observation-service.ts
Labels: WIP

#28 EPMXCUDA 6609. Test auth flow
  .gitignore
  README.md
  config/default.ts
  config/production.ts
  config/test.ts
  jest.config.json
  jestLoadConfig.ts
  lint-staged.config.js
  package-lock.json
  package.json
  src/app.ts
  src/controllers/auth-controller.spec.ts
  src/controllers/auth-controller.ts
  src/index.ts
  src/services/auth-service.ts
  src/tests/test.test.ts
  src/utils/CustomError.ts
  swagger.json
Labels: bug, enhancement

#31 feat/EPMCUXDA-6594 Implement importing euring based enitities
  package-lock.json
  package.json
  src/db/access-parser/EURING-access-tables.ts
  src/db/access-parser/run.ts
  src/entities/euring-codes/index.ts
  src/entities/euring-codes/species-entity.ts
  src/entities/euring-codes/status-of-ring-entity.ts
  src/entities/ring-entity.ts
  src/fixtures/Species.yml
  swagger.json
Labels: enhancement

#35 EPMCUXDA-6630,6635,6646: Add, edit and remove Observation
  src/controllers/observation-controller.ts
  src/entities/observation-entity.ts
  swagger.json
Labels: enhancement

#36 Epmcuxda 6640. Observation list and available filters
  package-lock.json
  package.json
  src/controllers/observation-controller.ts
  src/services/observation-service.ts
Labels: WIP, enhancement
