Repository abahachuk/ptushki-backend, pull requests merged in 2019-06, with the labels that each got.

#39 Epmcuxda 6874. Create endpoint for catalog data
  package-lock.json
  package.json
  src/controllers/catalog-controller.ts
  src/controllers/index.ts
  src/controllers/observation-controller.ts
  src/routes.ts
Labels: WIP

#41 Epmcuxda 6640. User role checking and 'lang' param
  config/default.ts
  src/controllers/observation-controller.ts
  src/services/observation-service.ts
Labels: WIP, enhancement

#44 EPMCUXDA-6946 update ring relation and field to store ring as string
  src/controllers/observation-controller.ts
  src/entities/observation-entity.ts
  src/fixtures/Observation.yml
  src/fixtures/ObservationProcessor.ts
  src/fixtures/RingProcessor.ts
  src/services/auth-service.ts
  swagger.json
Labels: fix

#45 EPMCUXDA-6938 Update models make some fields optional
  src/entities/observation-entity.ts
  src/fixtures/Age.yml
  src/fixtures/AgeProcessor.ts
  src/fixtures/CatchingLures.yml
  src/fixtures/CatchingLuresProcessor.ts
  src/fixtures/CatchingMethod.yml
  src/fixtures/CatchingMethodProcessor.ts
  src/fixtures/Manipulated.yml
  src/fixtures/ManipulatedProcessor.ts
  src/fixtures/MovedBeforeTheCapture.yml
  src/fixtures/MovedBeforeTheCaptureProcessor.ts
  src/fixtures/Sex.yml
  src/fixtures/SexProcessor.ts
  src/fixtures/Species.yml
  src/fixtures/SpeciesProcessor.ts
  src/fixtures/Status.yml
  src/fixtures/StatusProcessor.ts
Labels: enhancement, fix

#37 feat/EPMCUXDA 6851 initializing endpoint
  src/controllers/catalog-controller.ts
  src/controllers/index.ts
  src/controllers/initial-data-controller.ts
  src/entities/cached-repository.ts
  src/entities/euring-codes/cached-entities-fabric.ts
  src/entities/euring-codes/common-interfaces.ts
  src/entities/repositories-cache.ts
  src/entities/ring-entity.ts
  src/routes.ts
Labels: enhancement

#46 EPMCUXDA-6947 Generic Exporters & Importers
  src/controllers/observation-controller.ts
  src/entities/common-interfaces.ts
  src/entities/euring-codes/accuracy-of-coordinates-entity.ts
  src/entities/euring-codes/accuracy-of-date-entity.ts
  src/entities/euring-codes/accuracy-of-pullus-age-entity.ts
  src/entities/euring-codes/age-entity.ts
  src/entities/euring-codes/broodsize-entity.ts
  src/entities/euring-codes/catching-lures-entity.ts
  src/entities/euring-codes/catching-method-entity.ts
  src/entities/euring-codes/circumstances-entity.ts
  src/entities/euring-codes/circumstances-presumed-entity.ts
  src/entities/euring-codes/condition-entity.ts
  src/entities/euring-codes/euring-code-identifier-entity.ts
  src/entities/euring-codes/manipulated-entity.ts
  src/entities/euring-codes/metal-ring-information-entity.ts
  src/entities/euring-codes/moved-before-capture-entity.ts
  src/entities/euring-codes/other-marks-information-entity.ts
  src/entities/euring-codes/primary-identification-method-entity.ts
  src/entities/euring-codes/pullus-age-entity.ts
  src/entities/euring-codes/sex-entity.ts
  src/entities/euring-codes/species-entity.ts
  src/entities/euring-codes/status-entity.ts
  src/entities/euring-codes/status-of-ring-entity.ts
  src/entities/euring-codes/verification-of-the-metal-ring-entity.ts
  src/entities/observation-entity.ts
  src/entities/ring-entity.ts
  src/services/export/AbstractExporter.ts
  src/services/export/E2000PLUSExchangeCodeV117.pdf
  src/services/export/EURINGExporterForObservations.ts
  src/services/export/PDFExporterForObservations.ts
  src/services/export/XLSExporterForObservations.ts
  src/services/export/index.ts
  src/services/export/sample.xls
  src/services/import/AbstractImporter.ts
  src/services/import/EURINGImporterForObservations.ts
  src/services/import/XLSImporterForObservations.ts
  src/services/import/index.ts
  swagger.json
Labels: enhancement

#54 EPMCUXDA-6953 add photos field
  src/entities/observation-entity.ts
Labels: enhancement

#55 Fixing types issue in order to app started on server
  package-lock.json
  src/fixtures/ObservationProcessor.ts
Labels: bug

#57 EPMCUXDA-6851 Initialize initial-data endpoint more gently -- by heating up
  src/app.ts
  src/controllers/initial-data-controller.ts
  src/index.ts
  src/routes.ts
Labels: enhancement

#58 update flow for updating observation
  src/controllers/observation-controller.ts
Labels: enhancement, fix

#59 Epmcuxda 6805. Add exporting endpoint for observation
  package-lock.json
  package.json
  src/services/export/XLSExporterForObservations.ts
Labels: WIP

#63 Hotfix/update observation flow
  docs/observation.md
  src/entities/observation-entity.ts
  src/fixtures/Observation.yml
  src/fixtures/Species.yml
  swagger.json
Labels: enhancement

#56 Epmcuxda 6464 import parse
  src/controllers/upload-files-controller.ts
  src/services/export/XLSExporterTemplate.ts
  src/services/import/AbstractImporter.ts
  src/services/import/EURINGImporterForObservations.ts
  src/services/import/XLSImporterForObservations.ts
  src/services/import/excel-helper.ts
  src/services/import/excel/XLSImporterValidateObservations.ts
  src/services/import/excel/columns.ts
  src/services/import/excel/helper.ts
  src/services/import/excel/observation-format-validator.ts
  src/services/import/excel/properties.ts
  src/services/import/index.ts
Labels: enhancement

#64 EPMCUXDA-6640: introduce 'lang' param
  src/controllers/observation-controller.ts
  src/services/export/XLSExporterForObservations.ts
  src/services/observation-service.ts
Labels: enhancement
