Repository abahachuk/ptushki-backend, pull requests merged in 2020-03, with the labels that each got.

#77 fix: EPMCUXDA-7299 Combine importing xls endpoints on back-end
  src/controllers/observation-controller.ts
  src/services/import/AbstractImporter.ts
  src/services/import/XLSImporterForObservations.ts
  src/services/import/excel/XLSImporterValidateObservations.ts
  src/services/import/excel/columns.ts
  src/services/import/excel/helper.ts
  src/services/import/excel/observation-format-validator.ts
  src/services/import/index.ts
Labels: fix

#80 Feature: EPMCUXDA-7529 User places
  src/controllers/abstract-controller.ts
  src/controllers/users-controller.ts
  src/entities/submodels/UserPlace.ts
  src/entities/user-entity.ts
Labels: enhancement

#60 EPMCUXDA-6683: add mail client, forgot/reset password api logic
  config/default.ts
  config/production.ts
  package-lock.json
  package.json
  src/app.ts
  src/controllers/abstract-controller.ts
  src/controllers/auth-controller.spec.ts
  src/controllers/auth-controller.ts
  src/controllers/initial-data-controller.ts
  src/entities/auth-entity.ts
  src/entities/reset-token.ts
  src/services/auth-service.ts
  src/services/mail-service/MailSender.ts
  src/services/mail-service/index.ts
  src/templates/mail.ts
  swagger.config.yml
  swagger.json
Labels: WIP, enhancement

#83 fix: observations aggregation with null values
  src/controllers/observation-controller.ts
Labels: bug, critical
